"""Intake summary + compliance check via Claude (spec §9, §10).

Two independent LLM calls per transcript:
  1. summary     -> the §10 JSON schema, stored in `summaries.summary`
  2. compliance  -> {flag, notes}: did the AI assistant give any medical advice?

Both use structured outputs, so the model's JSON is validated against a
Pydantic schema by the SDK. A summary that still fails after one retry is
stored as "Summary failed — see transcript" (spec §10); a failed compliance
check is stored as *flagged*, so a human looks at the transcript.

Summaries are generated by a background job (summary worker), never inside
the webhook request, because an LLM call can take tens of seconds.
"""

import logging
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, TypeVar
from uuid import UUID

import anthropic
from psycopg.types.json import Jsonb
from pydantic import BaseModel, Field

from app import config
from app.config import get_settings
from app.db import transaction

log = logging.getLogger("clinic.summary")

PROMPTS = Path(__file__).resolve().parents[1] / "prompts"
FALLBACK_BETA = "server-side-fallback-2026-07-01"
# Server-side refusal fallback exists only for these models; other models (e.g. Haiku) get a plain request.
FALLBACK_MODELS = {"claude-opus-5", "claude-opus-5-5", "claude-fable-5", "claude-fable-5-1"}
SUMMARY_FAILED_NOTE = "Summary failed — see transcript"

T = TypeVar("T", bound=BaseModel)


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class SpecialtyAnswer(BaseModel):
    question: str
    answer: str


class IntakeSummary(BaseModel):
    """What the model returns. Stored with specialty_answers as a {question: answer} map (spec §10)."""

    chief_complaint: str
    duration: str
    severity: Literal["mild", "moderate", "severe", "not mentioned"]
    symptoms: list[str]
    current_medicines: list[str]
    allergies: list[str]
    past_treatments: list[str]
    specialty_answers: list[SpecialtyAnswer]
    patient_questions: list[str]
    hospital_advice_given: bool = Field(description='True if the assistant told the patient to visit a hospital.')
    language: Literal["ta", "en", "hi"]
    notes: str

    def to_record(self) -> dict[str, Any]:
        data = self.model_dump()
        data["specialty_answers"] = {a.question: a.answer for a in self.specialty_answers}
        return data


class ComplianceResult(BaseModel):
    flag: bool
    notes: str


# ---------------------------------------------------------------------------
# Claude API
# ---------------------------------------------------------------------------

class LLMError(Exception):
    """Permanent failure for this input (refusal, invalid output, bad request)."""


class LLMUnavailable(Exception):
    """Transient or configuration problem — try again later, don't record a failure."""


def is_configured() -> bool:
    return bool(get_settings().llm_api_key)


@lru_cache
def _client() -> anthropic.Anthropic:
    # The SDK retries 408/409/429/5xx and connection errors itself (max_retries).
    return anthropic.Anthropic(api_key=get_settings().llm_api_key, timeout=120.0, max_retries=2)


@lru_cache
def _prompt(name: str) -> str:
    return (PROMPTS / name).read_text(encoding="utf-8")


def llm_parse(schema: type[T], system: str, content: str) -> T:
    """One structured-output request. Returns the validated model or raises LLMError / LLMUnavailable."""
    model = get_settings().llm_model
    extra: dict[str, Any] = {}
    if model in FALLBACK_MODELS:
        # If a safety classifier declines, re-run on Anthropic's recommended fallback model.
        extra = {"betas": [FALLBACK_BETA], "fallbacks": "default"}
    try:
        response = _client().beta.messages.parse(
            model=model,
            max_tokens=16000,
            system=system,
            messages=[{"role": "user", "content": content}],
            output_format=schema,
            **extra,
        )
    except (anthropic.AuthenticationError, anthropic.PermissionDeniedError, anthropic.NotFoundError) as exc:
        raise LLMUnavailable(f"Claude API configuration problem: {exc}") from exc
    except (anthropic.RateLimitError, anthropic.APIConnectionError, anthropic.InternalServerError) as exc:
        raise LLMUnavailable(f"Claude API temporarily unavailable: {exc}") from exc
    except anthropic.APIStatusError as exc:
        if exc.status_code >= 500:
            raise LLMUnavailable(f"Claude API error {exc.status_code}") from exc
        raise LLMError(f"Claude API rejected the request ({exc.status_code}): {exc.message}") from exc
    except ValueError as exc:  # pydantic ValidationError / invalid JSON from the parse helper
        raise LLMError(f"Output did not match the schema: {exc}") from exc

    if response.stop_reason == "refusal":
        category = getattr(response.stop_details, "category", None)
        raise LLMError(f"Claude declined (category: {category})")
    if response.stop_reason == "max_tokens":
        raise LLMError("Output was cut off (max_tokens)")
    if response.parsed_output is None:
        raise LLMError("No structured output in the response")
    return response.parsed_output


# ---------------------------------------------------------------------------
# Prompt building
# ---------------------------------------------------------------------------

def format_transcript(transcript: list[dict[str, Any]] | None) -> str:
    lines = []
    for turn in transcript or []:
        message = (turn.get("message") or "").strip()
        if not message:
            continue
        speaker = "Patient" if turn.get("role") == "user" else "AI assistant"
        lines.append(f"{speaker}: {message}")
    return "\n".join(lines)


def summary_request(transcript_text: str, language: str, specialty: str) -> str:
    questions = config.SPECIALTY_QUESTIONS.get(specialty.lower(), [])
    q = "\n".join(f"- {x}" for x in questions) or "- (none)"
    return (
        f"Patient's chosen language when booking: {language}\n"
        f"Specialty questions the assistant was asked to cover (use these as the "
        f"specialty_answers questions; answer 'not mentioned' if not answered):\n{q}\n\n"
        f"<transcript>\n{transcript_text}\n</transcript>"
    )


def compliance_request(transcript_text: str) -> str:
    return f"<transcript>\n{transcript_text}\n</transcript>"


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def generate_summary(transcript_text: str, language: str, specialty: str) -> dict[str, Any]:
    """Summary JSON; retries once on invalid output, then returns the 'failed' placeholder."""
    content = summary_request(transcript_text, language, specialty)
    for attempt in (1, 2):
        try:
            return llm_parse(IntakeSummary, _prompt("summary_prompt.md"), content).to_record()
        except LLMError as exc:
            log.warning("Summary attempt %d failed: %s", attempt, exc)
    return failed_summary(language)


def failed_summary(language: str) -> dict[str, Any]:
    return {
        "chief_complaint": "not mentioned",
        "duration": "not mentioned",
        "severity": "not mentioned",
        "symptoms": [],
        "current_medicines": [],
        "allergies": [],
        "past_treatments": [],
        "specialty_answers": {},
        "patient_questions": [],
        "hospital_advice_given": False,
        "language": language if language in ("ta", "en", "hi") else "en",
        "notes": SUMMARY_FAILED_NOTE,
    }


def check_compliance(transcript_text: str) -> ComplianceResult:
    """Did the assistant give advice? If the check itself fails, flag it for a human."""
    try:
        return llm_parse(ComplianceResult, _prompt("compliance_prompt.md"), compliance_request(transcript_text))
    except LLMError as exc:
        log.warning("Compliance check failed: %s", exc)
        return ComplianceResult(flag=True, notes=f"Automatic check failed ({exc}). Please review the transcript.")


# ---------------------------------------------------------------------------
# Worker
# ---------------------------------------------------------------------------

_PENDING_SQL = """
select c.id as call_id, c.appointment_id, c.transcript, a.preferred_language, d.specialty
from calls c
join appointments a on a.id = c.appointment_id
join slots s on s.id = a.slot_id
join doctors d on d.id = s.doctor_id
where c.status = 'COMPLETED'
  and not exists (select 1 from summaries sm where sm.appointment_id = c.appointment_id)
order by c.ended_at nulls last
limit %s
"""


def summarize_call(row: dict[str, Any]) -> bool:
    """Generate and store summary + compliance for one completed call. Returns True if stored."""
    text = format_transcript(row["transcript"])
    summary = generate_summary(text, row["preferred_language"], row["specialty"])
    compliance = check_compliance(text)
    with transaction() as conn:
        cur = conn.execute(
            """
            insert into summaries (appointment_id, source, summary, compliance_flag, compliance_notes)
            values (%s, 'CALL', %s, %s, %s)
            on conflict (appointment_id) do nothing
            """,
            (row["appointment_id"], Jsonb(summary), compliance.flag, compliance.notes or None),
        )
    return cur.rowcount == 1


def process_pending_summaries(limit: int = 5) -> int:
    """Summarise completed calls that don't have a summary yet. Returns how many were stored."""
    if not is_configured():
        return 0
    with transaction() as conn:
        rows = conn.execute(_PENDING_SQL, (limit,)).fetchall()
    stored = 0
    for row in rows:
        try:
            if summarize_call(row):
                stored += 1
                log.info("Summary stored for appointment %s", row["appointment_id"])
        except LLMUnavailable as exc:
            # Leave it for the next run; no point hammering a down/misconfigured API.
            log.warning("Summary postponed: %s", exc)
            break
    return stored
